### PR TITLE
Use Polymer.Base

### PR DESCRIPTION
**Pull request by benoitjchevalier**
Don't think Polymer.base is a thing unless I missed something :)

### CODE REVIEW

**Comment by benoitjchevalier** [comment]
I already signed the CLA as part of the GE google group

**Comment by e111077** [comment]
Odd that this hasn't been reported before

**Comment by arthurevans** [comment]
Note in Polymer 2.x this will fail if the user imports `polymer-element.html` but not `polymer.html`. So the logic should be `if (window.Polymer && Polymer.Base)` to avoid failure.

Or if you want to get fancy, you could take advantage of `Polymer.Async` in 2.x if it's been imported:

```
if (window.Polymer && Polymer.Base) { ... } 
else if (window.Polymer && Polymer.Async) {
  asap = Polymer.Async.microTask.run;
}
asap || asap = window.setTimeout
```
Or words to that effect. As to why this hasn't been reported: I notice that there's no issue list on this repo... Also, it would only fail on IE, and people have been having other trouble with IE (i.e., a bug in PSK that was keeping it from working on IE).

**Comment by e111077** [comment]
Thanks for the notification Arthur! Issues are open

**Pull request merged**
